In [57]:
import pandas as pd
df=pd.read_csv('D:\\data\\diabetics.csv')
df.head()

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            6      148             72             35        0  33.6   
1            1       85             66             29        0  26.6   
2            8      183             64              0        0  23.3   
3            1       89             66             23       94  28.1   
4            0      137             40             35      168  43.1   

   DiabetesPedigreeFunction  Age  Outcome  
0                     0.627   50        1  
1                     0.351   31        0  
2                     0.672   32        1  
3                     0.167   21        0  
4                     2.288   33        1

In [58]:
import numpy as np

In [59]:
import warnings
warnings.filterwarnings('ignore')

In [60]:
(df==0).sum()

Pregnancies                 111
Glucose                       5
BloodPressure                35
SkinThickness               227
Insulin                     374
BMI                          11
DiabetesPedigreeFunction      0
Age                           0
Outcome                     500
dtype: int64

In [61]:
#GM=df['Glucose'].median()
#df['Glucose']=df['Glucose'].replace(0,GM)
df['Glucose']=np.where(df['Glucose']==0,df['Glucose'].median(),df['Glucose'])
df['Insulin']=np.where(df['Insulin']==0,df['Insulin'].median(),df['Insulin'])
df['SkinThickness']=np.where(df['SkinThickness']==0,df['SkinThickness'].median(),df['SkinThickness'])
df['BloodPressure']=np.where(df['BloodPressure']==0,df['BloodPressure'].median(),df['BloodPressure'])
df['BMI']=np.where(df['BMI']==0,df['BMI'].median(),df['BMI'])

(df==0).sum()

Pregnancies                 111
Glucose                       0
BloodPressure                 0
SkinThickness                 0
Insulin                       0
BMI                           0
DiabetesPedigreeFunction      0
Age                           0
Outcome                     500
dtype: int64

In [62]:
df.head()

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            6    148.0           72.0           35.0     30.5  33.6   
1            1     85.0           66.0           29.0     30.5  26.6   
2            8    183.0           64.0           23.0     30.5  23.3   
3            1     89.0           66.0           23.0     94.0  28.1   
4            0    137.0           40.0           35.0    168.0  43.1   

   DiabetesPedigreeFunction  Age  Outcome  
0                     0.627   50        1  
1                     0.351   31        0  
2                     0.672   32        1  
3                     0.167   21        0  
4                     2.288   33        1

In [63]:
X=df.drop(['Outcome'],axis=1)
X.head()

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            6    148.0           72.0           35.0     30.5  33.6   
1            1     85.0           66.0           29.0     30.5  26.6   
2            8    183.0           64.0           23.0     30.5  23.3   
3            1     89.0           66.0           23.0     94.0  28.1   
4            0    137.0           40.0           35.0    168.0  43.1   

   DiabetesPedigreeFunction  Age  
0                     0.627   50  
1                     0.351   31  
2                     0.672   32  
3                     0.167   21  
4                     2.288   33

In [64]:
y=df.Outcome
y.head()

0    1
1    0
2    1
3    0
4    1
Name: Outcome, dtype: int64

In [65]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test =train_test_split(X,y,test_size=.2,random_state=33)

In [66]:
from sklearn.ensemble import RandomForestClassifier
r_cl=RandomForestClassifier(n_estimators=10).fit(X_train,y_train)
prediction=r_cl.predict(X_test)

In [67]:
from sklearn.metrics import confusion_matrix,accuracy_score,classification_report
print(confusion_matrix(y_test,prediction))


[[83 16]
 [31 24]]


In [68]:
print(accuracy_score(y_test,prediction))


0.6948051948051948


In [69]:
print(classification_report(y_test,prediction))

              precision    recall  f1-score   support

           0       0.73      0.84      0.78        99
           1       0.60      0.44      0.51        55

    accuracy                           0.69       154
   macro avg       0.66      0.64      0.64       154
weighted avg       0.68      0.69      0.68       154



## RandomizedSearchCV

In [70]:
##Randomly select for finding hyperparams 
import numpy as np
from sklearn.model_selection import RandomizedSearchCV
model=RandomForestClassifier()

In [71]:
[int(x) for x in np.linspace(start=200,stop=2000,num=10)]

[200, 400, 600, 800, 1000, 1200, 1400, 1600, 1800, 2000]

In [96]:

# number of trees in random forest
n_estimators=[int(x) for x in np.linspace(start=100,stop=2000,num=10)]
#number of features to consider at every split
max_features=["auto", "sqrt", "log2"]
##max number of level in tree
max_depth=[int(x) for x in np.linspace(10,1000,10)]
##minimum number of sample to split a node
min_samples_split=[1,2,3,4,5,7,9]
#minimum number of samples to split a each leaf node
min_samples_leaf=[1,2,4,6,8]
#create random grid
random_grid={
    "n_estimators":n_estimators,
    "max_features":max_features,
    "max_depth":max_depth,
    "min_samples_split":min_samples_split,
    "min_samples_leaf":min_samples_leaf,
    'criterion':['gini', "entropy"]
    
}

In [73]:
randm_cv=RandomizedSearchCV(estimator=RandomForestClassifier(),param_distributions=random_grid,n_iter=100,cv=3,random_state=100,n_jobs=-1)
randm_cv.fit(X_train,y_train)


RandomizedSearchCV(cv=3, estimator=RandomForestClassifier(), n_iter=100,
                   n_jobs=-1,
                   param_distributions={'criterion': ['gini', 'entropy'],
                                        'max_depth': [10, 120, 230, 340, 450,
                                                      560, 670, 780, 890,
                                                      1000],
                                        'max_features': ['auto', 'sqrt',
                                                         'log2'],
                                        'min_samples_leaf': [1, 2, 4, 6, 8],
                                        'min_samples_split': [1, 2, 3, 4, 5, 7,
                                                              9],
                                        'n_estimators': [100, 311, 522, 733,
                                                         944, 1155, 1366, 1577,
                                                         1788, 2000]},
                   r

In [74]:
randm_cv.best_params_

{'n_estimators': 311,
 'min_samples_split': 5,
 'min_samples_leaf': 8,
 'max_features': 'log2',
 'max_depth': 120,
 'criterion': 'entropy'}

In [75]:
best_random_grid=randm_cv.best_estimator_

In [76]:
predicton_randomgrid=best_random_grid.predict(X_test)
print(confusion_matrix(y_test,predicton_randomgrid))
print(accuracy_score(y_test,predicton_randomgrid))

[[84 15]
 [23 32]]
0.7532467532467533


## GridsearcCV

In [77]:
from sklearn.model_selection import GridSearchCV
params={
    "n_estimators":[randm_cv.best_params_['n_estimators']+200,
                   randm_cv.best_params_['n_estimators']-100,
                   randm_cv.best_params_['n_estimators'],
                   randm_cv.best_params_['n_estimators']+100,
                   randm_cv.best_params_['n_estimators']+200],
    "max_features":[randm_cv.best_params_['max_features']],
    "max_depth":[randm_cv.best_params_['max_depth']],
    "min_samples_split":[randm_cv.best_params_['min_samples_split']+2,
                         randm_cv.best_params_['min_samples_split']+1,
                         randm_cv.best_params_['min_samples_split']-2,
                         randm_cv.best_params_['min_samples_split']-1],
    "min_samples_leaf":[randm_cv.best_params_['min_samples_leaf'],
                        randm_cv.best_params_['min_samples_leaf']+2,
                        randm_cv.best_params_['min_samples_leaf']+4],
    'criterion':[randm_cv.best_params_['criterion']]
         }
print(params)

{'n_estimators': [511, 211, 311, 411, 511], 'max_features': ['log2'], 'max_depth': [120], 'min_samples_split': [7, 6, 3, 4], 'min_samples_leaf': [8, 10, 12], 'criterion': ['entropy']}


In [78]:
5*1*1*4*3*1#iteration we should take

60

In [79]:
gcv=GridSearchCV(estimator=RandomForestClassifier(),param_grid=params,cv=10,n_jobs=-1,verbose=2)
gcv.fit(X_train,y_train)

Fitting 10 folds for each of 60 candidates, totalling 600 fits


GridSearchCV(cv=10, estimator=RandomForestClassifier(), n_jobs=-1,
             param_grid={'criterion': ['entropy'], 'max_depth': [120],
                         'max_features': ['log2'],
                         'min_samples_leaf': [8, 10, 12],
                         'min_samples_split': [7, 6, 3, 4],
                         'n_estimators': [511, 211, 311, 411, 511]},
             verbose=2)

In [80]:
gcv.best_params_

{'criterion': 'entropy',
 'max_depth': 120,
 'max_features': 'log2',
 'min_samples_leaf': 12,
 'min_samples_split': 7,
 'n_estimators': 511}

In [81]:
best_grid_cv=gcv.best_estimator_

In [82]:
gcv_prediction=best_grid_cv.predict(X_test)

In [83]:
print(confusion_matrix(y_test,gcv_prediction))

[[85 14]
 [28 27]]


In [84]:
print(accuracy_score(y_test,gcv_prediction))

0.7272727272727273


## Baysian Optimization

In [85]:
from hyperopt import hp,fmin,tpe,STATUS_OK,Trials

In [86]:
space={
    'criterion':hp.choice('criterion',['entropy','gini']),
    'max_depth':hp.quniform('max_depth',10,1200,10),
    'max_features':hp.choice('max_features',['auto','sqrt','log2',None]),
    'min_samples_leaf':hp.uniform('min_samples_leaf',0,0.5),
    'min_samples_split':hp.uniform('min_samples_split',0,3),
    'n_estimators':hp.choice('n_estimators',[10,50,300,750,1000])
    }
space

{'criterion': <hyperopt.pyll.base.Apply at 0x1c54ec4a190>,
 'max_depth': <hyperopt.pyll.base.Apply at 0x1c54f6d4f70>,
 'max_features': <hyperopt.pyll.base.Apply at 0x1c54f6d40d0>,
 'min_samples_leaf': <hyperopt.pyll.base.Apply at 0x1c54f6d4430>,
 'min_samples_split': <hyperopt.pyll.base.Apply at 0x1c54f6d4f40>,
 'n_estimators': <hyperopt.pyll.base.Apply at 0x1c54f6d4b50>}

In [87]:
from sklearn.model_selection import cross_val_score

In [88]:
space['criterion']

In [89]:
from statistics import mean
def objective(space):
    model3=RandomForestClassifier(criterion=space['criterion'],max_depth=space['max_depth'],max_features=space['max_features'],min_samples_leaf=space['min_samples_leaf'],min_samples_split=space['min_samples_split'],n_estimators=space['n_estimators'])
    print(model3)
    accuracy= cross_val_score(model3,X_train,y_train,cv=5).mean()
    print(accuracy)
    #WE AIM TO Maximise accuracy therefore we return it as negative value
    return{'loss': -accuracy,'status': STATUS_OK}
objective(space)

RandomForestClassifier(criterion=<hyperopt.pyll.base.Apply object at 0x000001C54EC4A190>,
                       max_depth=<hyperopt.pyll.base.Apply object at 0x000001C54F6D4F70>,
                       max_features=<hyperopt.pyll.base.Apply object at 0x000001C54F6D40D0>,
                       min_samples_leaf=<hyperopt.pyll.base.Apply object at 0x000001C54F6D4430>,
                       min_samples_split=<hyperopt.pyll.base.Apply object at 0x000001C54F6D4F40>,
                       n_estimators=<hyperopt.pyll.base.Apply object at 0x000001C54F6D4B50>)
nan


{'loss': nan, 'status': 'ok'}

In [90]:
from sklearn.model_selection import cross_val_score
trial=Trials()
best= fmin(fn=objective,
         space=space,
         algo=tpe.suggest,
         max_evals=80,
         trials=trial)
best

RandomForestClassifier(max_depth=1190.0, max_features='sqrt',                                                          
                       min_samples_leaf=0.23723264841581282,
                       min_samples_split=2.8189887537783522, n_estimators=750)
nan                                                                                                                    
RandomForestClassifier(max_depth=370.0, max_features=None,                                                             
                       min_samples_leaf=0.2578153649983876,
                       min_samples_split=1.5585226256345328, n_estimators=300)
nan                                                                                                                    
RandomForestClassifier(max_depth=900.0, max_features='log2',                                                           
                       min_samples_leaf=0.4998818799541074,
                       min_samples_split=0.2431837155544615, 

RandomForestClassifier(max_depth=1110.0, min_samples_leaf=0.15174743589990186,                                         
                       min_samples_split=2.982368822946694, n_estimators=750)
nan                                                                                                                    
RandomForestClassifier(criterion='entropy', max_depth=990.0, max_features=None,                                        
                       min_samples_leaf=0.4106853832828608,
                       min_samples_split=0.9248431907910634, n_estimators=50)
0.6530987604958016                                                                                                     
RandomForestClassifier(criterion='entropy', max_depth=120.0,                                                           
                       min_samples_leaf=0.1481257246261749,
                       min_samples_split=0.8247129784260633, n_estimators=750)
0.6530987604958016                           

RandomForestClassifier(criterion='entropy', max_depth=160.0, max_features=None,                                        
                       min_samples_leaf=0.1037390928800766,
                       min_samples_split=2.871275524543732, n_estimators=300)
nan                                                                                                                    
RandomForestClassifier(max_depth=790.0, max_features=None,                                                             
                       min_samples_leaf=0.0663029226681654,
                       min_samples_split=1.1679554732968194, n_estimators=750)
nan                                                                                                                    
RandomForestClassifier(criterion='entropy', max_depth=110.0,                                                           
                       min_samples_leaf=0.38605734962751387,
                       min_samples_split=0.9596930818233393, n

nan                                                                                                                    
RandomForestClassifier(max_depth=770.0, max_features='sqrt',                                                           
                       min_samples_leaf=0.27983661777574487,
                       min_samples_split=2.5728064356837446, n_estimators=300)
nan                                                                                                                    
RandomForestClassifier(max_depth=760.0, max_features='sqrt',                                                           
                       min_samples_leaf=0.2618970418781573,
                       min_samples_split=2.267164162465822, n_estimators=300)
nan                                                                                                                    
RandomForestClassifier(max_depth=770.0, max_features='sqrt',                                                           
  

{'criterion': 1,
 'max_depth': 680.0,
 'max_features': 2,
 'min_samples_leaf': 0.1970547495683468,
 'min_samples_split': 0.5835373092307925,
 'n_estimators': 2}

In [91]:
crit={0:'entropy',1:'gini'}
features={ 0:'auto',1:'sqrt',2:'log2',3:None}
estimators={0:10,1:50,2:300,3:750,4:1000}


In [92]:
estimators[best['n_estimators']]

300

In [93]:
model4=RandomForestClassifier(criterion=crit[best['criterion']],max_depth=best['max_depth'],max_features=features[best['max_features']],min_samples_leaf=best['min_samples_leaf'],min_samples_split=best['min_samples_split'],n_estimators=estimators[best['n_estimators']])

In [94]:
model4.fit(X_train,y_train)

RandomForestClassifier(max_depth=680.0, max_features='log2',
                       min_samples_leaf=0.1970547495683468,
                       min_samples_split=0.5835373092307925, n_estimators=300)

In [95]:
predic_forest=model4.predict(X_test)
print(confusion_matrix(predic_forest,y_test))
print(accuracy_score(predic_forest,y_test))

[[94 43]
 [ 5 12]]
0.6883116883116883


## Genetic ALgotiyhm

In [124]:
import numpy as np
#from sklearn.ensemble import RandomForestClassifier

In [125]:
# number of trees in random forest
n_estimators=[int(x) for x in np.linspace(start=100,stop=2000,num=10)]
#number of features to consider at every split
max_features=["auto", "sqrt", "log2"]
##max number of level in tree
max_depth=[int(x) for x in np.linspace(10,1000,10)]
##minimum number of sample to split a node
min_samples_split=[1,2,3,4,5,7,9]
#minimum number of samples to split a each leaf node
min_samples_leaf=[1,2,4,6,8]
#create random grid
param={
    "n_estimators":n_estimators,
    "max_features":max_features,
    "max_depth":max_depth,
    "min_samples_split":min_samples_split,
    "min_samples_leaf":min_samples_leaf,
    'criterion':['gini', "entropy"]
    
}

In [141]:
from tpot import TPOTClassifier

In [155]:
k=sklearn.ensemble.RandomForestClassifier(n)

In [158]:
TPOT_classifier=TPOTClassifier(generations=5,population_size=23,offspring_size=12,
                               config_dict={'sklearn.ensemble.RandomForestClassifier':params},
                               early_stop=12,verbosity=2,cv=4,scoring='accuracy')


In [159]:
TPOT_classifier.fit(X_train,y_train)

AssertionError: Terminals are required to have a unique name. Consider using the argument 'name' to rename your second RandomForestClassifier__n_estimators=511 terminal.